name: animate
description: "Anim-X: A premium animation app for creators."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  flutter_colorpicker: ^1.1.0
  google_fonts: ^6.2.1
  path_provider: ^2.1.2
  image: ^4.2.0
  uuid: ^4.4.0
  path: ^1.9.0
  image_picker: ^1.1.2
  media_kit: ^1.1.10
  media_kit_video: ^1.2.4
  media_kit_libs_video: ^1.0.7
  ffmpeg_kit_flutter_min_gpl: ^6.0.3
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  google_mobile_ads: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
